// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agentfs.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLatestSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestSnapshotRequest) Reset() {
	*x = GetLatestSnapshotRequest{}
	mi := &file_agentfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSnapshotRequest) ProtoMessage() {}

func (x *GetLatestSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetLatestSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{0}
}

func (x *GetLatestSnapshotRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type GetLatestSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SnapshotMetadata      `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestSnapshotResponse) Reset() {
	*x = GetLatestSnapshotResponse{}
	mi := &file_agentfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSnapshotResponse) ProtoMessage() {}

func (x *GetLatestSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetLatestSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{1}
}

func (x *GetLatestSnapshotResponse) GetSnapshot() *SnapshotMetadata {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type UploadSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Snapshot      *SnapshotMetadata      `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSnapshotRequest) Reset() {
	*x = UploadSnapshotRequest{}
	mi := &file_agentfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSnapshotRequest) ProtoMessage() {}

func (x *UploadSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSnapshotRequest.ProtoReflect.Descriptor instead.
func (*UploadSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{2}
}

func (x *UploadSnapshotRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *UploadSnapshotRequest) GetSnapshot() *SnapshotMetadata {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type UploadSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSnapshotResponse) Reset() {
	*x = UploadSnapshotResponse{}
	mi := &file_agentfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSnapshotResponse) ProtoMessage() {}

func (x *UploadSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSnapshotResponse.ProtoReflect.Descriptor instead.
func (*UploadSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{3}
}

func (x *UploadSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SnapshotMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileMetadata        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotMetadata) Reset() {
	*x = SnapshotMetadata{}
	mi := &file_agentfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMetadata) ProtoMessage() {}

func (x *SnapshotMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMetadata.ProtoReflect.Descriptor instead.
func (*SnapshotMetadata) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotMetadata) GetFiles() []*FileMetadata {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_agentfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{5}
}

func (x *FileMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileMetadata) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *FileMetadata) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type UploadBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadBlobRequest_Sha256
	//	*UploadBlobRequest_Content
	Data          isUploadBlobRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBlobRequest) Reset() {
	*x = UploadBlobRequest{}
	mi := &file_agentfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlobRequest) ProtoMessage() {}

func (x *UploadBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlobRequest.ProtoReflect.Descriptor instead.
func (*UploadBlobRequest) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{6}
}

func (x *UploadBlobRequest) GetData() isUploadBlobRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadBlobRequest) GetSha256() string {
	if x != nil {
		if x, ok := x.Data.(*UploadBlobRequest_Sha256); ok {
			return x.Sha256
		}
	}
	return ""
}

func (x *UploadBlobRequest) GetContent() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadBlobRequest_Content); ok {
			return x.Content
		}
	}
	return nil
}

type isUploadBlobRequest_Data interface {
	isUploadBlobRequest_Data()
}

type UploadBlobRequest_Sha256 struct {
	Sha256 string `protobuf:"bytes,1,opt,name=sha256,proto3,oneof"`
}

type UploadBlobRequest_Content struct {
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*UploadBlobRequest_Sha256) isUploadBlobRequest_Data() {}

func (*UploadBlobRequest_Content) isUploadBlobRequest_Data() {}

type UploadBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBlobResponse) Reset() {
	*x = UploadBlobResponse{}
	mi := &file_agentfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlobResponse) ProtoMessage() {}

func (x *UploadBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlobResponse.ProtoReflect.Descriptor instead.
func (*UploadBlobResponse) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{7}
}

func (x *UploadBlobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DownloadBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBlobRequest) Reset() {
	*x = DownloadBlobRequest{}
	mi := &file_agentfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBlobRequest) ProtoMessage() {}

func (x *DownloadBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBlobRequest.ProtoReflect.Descriptor instead.
func (*DownloadBlobRequest) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadBlobRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type DownloadBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBlobResponse) Reset() {
	*x = DownloadBlobResponse{}
	mi := &file_agentfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBlobResponse) ProtoMessage() {}

func (x *DownloadBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBlobResponse.ProtoReflect.Descriptor instead.
func (*DownloadBlobResponse) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadBlobResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type HasBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasBlobRequest) Reset() {
	*x = HasBlobRequest{}
	mi := &file_agentfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasBlobRequest) ProtoMessage() {}

func (x *HasBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasBlobRequest.ProtoReflect.Descriptor instead.
func (*HasBlobRequest) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{10}
}

func (x *HasBlobRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type HasBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasBlobResponse) Reset() {
	*x = HasBlobResponse{}
	mi := &file_agentfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasBlobResponse) ProtoMessage() {}

func (x *HasBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasBlobResponse.ProtoReflect.Descriptor instead.
func (*HasBlobResponse) Descriptor() ([]byte, []int) {
	return file_agentfs_proto_rawDescGZIP(), []int{11}
}

func (x *HasBlobResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_agentfs_proto protoreflect.FileDescriptor

const file_agentfs_proto_rawDesc = "" +
	"\n" +
	"\ragentfs.proto\x12\x10agentfs.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\x18GetLatestSnapshotRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"[\n" +
	"\x19GetLatestSnapshotResponse\x12>\n" +
	"\bsnapshot\x18\x01 \x01(\v2\".agentfs.v1alpha1.SnapshotMetadataR\bsnapshot\"t\n" +
	"\x15UploadSnapshotRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12>\n" +
	"\bsnapshot\x18\x02 \x01(\v2\".agentfs.v1alpha1.SnapshotMetadataR\bsnapshot\"2\n" +
	"\x16UploadSnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\x10SnapshotMetadata\x124\n" +
	"\x05files\x18\x01 \x03(\v2\x1e.agentfs.v1alpha1.FileMetadataR\x05files\"\x99\x01\n" +
	"\fFileMetadata\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\"Q\n" +
	"\x11UploadBlobRequest\x12\x18\n" +
	"\x06sha256\x18\x01 \x01(\tH\x00R\x06sha256\x12\x1a\n" +
	"\acontent\x18\x02 \x01(\fH\x00R\acontentB\x06\n" +
	"\x04data\".\n" +
	"\x12UploadBlobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x13DownloadBlobRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\"0\n" +
	"\x14DownloadBlobResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"(\n" +
	"\x0eHasBlobRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\")\n" +
	"\x0fHasBlobResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\xf2\x03\n" +
	"\x11AgentFSController\x12l\n" +
	"\x11GetLatestSnapshot\x12*.agentfs.v1alpha1.GetLatestSnapshotRequest\x1a+.agentfs.v1alpha1.GetLatestSnapshotResponse\x12c\n" +
	"\x0eUploadSnapshot\x12'.agentfs.v1alpha1.UploadSnapshotRequest\x1a(.agentfs.v1alpha1.UploadSnapshotResponse\x12Y\n" +
	"\n" +
	"UploadBlob\x12#.agentfs.v1alpha1.UploadBlobRequest\x1a$.agentfs.v1alpha1.UploadBlobResponse(\x01\x12_\n" +
	"\fDownloadBlob\x12%.agentfs.v1alpha1.DownloadBlobRequest\x1a&.agentfs.v1alpha1.DownloadBlobResponse0\x01\x12N\n" +
	"\aHasBlob\x12 .agentfs.v1alpha1.HasBlobRequest\x1a!.agentfs.v1alpha1.HasBlobResponseBQZOgithub.com/gke-labs/generation-ai/experiments/agentfs/pkg/api/v1alpha1;v1alpha1b\x06proto3"

var (
	file_agentfs_proto_rawDescOnce sync.Once
	file_agentfs_proto_rawDescData []byte
)

func file_agentfs_proto_rawDescGZIP() []byte {
	file_agentfs_proto_rawDescOnce.Do(func() {
		file_agentfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentfs_proto_rawDesc), len(file_agentfs_proto_rawDesc)))
	})
	return file_agentfs_proto_rawDescData
}

var file_agentfs_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agentfs_proto_goTypes = []any{
	(*GetLatestSnapshotRequest)(nil),  // 0: agentfs.v1alpha1.GetLatestSnapshotRequest
	(*GetLatestSnapshotResponse)(nil), // 1: agentfs.v1alpha1.GetLatestSnapshotResponse
	(*UploadSnapshotRequest)(nil),     // 2: agentfs.v1alpha1.UploadSnapshotRequest
	(*UploadSnapshotResponse)(nil),    // 3: agentfs.v1alpha1.UploadSnapshotResponse
	(*SnapshotMetadata)(nil),          // 4: agentfs.v1alpha1.SnapshotMetadata
	(*FileMetadata)(nil),              // 5: agentfs.v1alpha1.FileMetadata
	(*UploadBlobRequest)(nil),         // 6: agentfs.v1alpha1.UploadBlobRequest
	(*UploadBlobResponse)(nil),        // 7: agentfs.v1alpha1.UploadBlobResponse
	(*DownloadBlobRequest)(nil),       // 8: agentfs.v1alpha1.DownloadBlobRequest
	(*DownloadBlobResponse)(nil),      // 9: agentfs.v1alpha1.DownloadBlobResponse
	(*HasBlobRequest)(nil),            // 10: agentfs.v1alpha1.HasBlobRequest
	(*HasBlobResponse)(nil),           // 11: agentfs.v1alpha1.HasBlobResponse
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_agentfs_proto_depIdxs = []int32{
	4,  // 0: agentfs.v1alpha1.GetLatestSnapshotResponse.snapshot:type_name -> agentfs.v1alpha1.SnapshotMetadata
	4,  // 1: agentfs.v1alpha1.UploadSnapshotRequest.snapshot:type_name -> agentfs.v1alpha1.SnapshotMetadata
	5,  // 2: agentfs.v1alpha1.SnapshotMetadata.files:type_name -> agentfs.v1alpha1.FileMetadata
	12, // 3: agentfs.v1alpha1.FileMetadata.mod_time:type_name -> google.protobuf.Timestamp
	0,  // 4: agentfs.v1alpha1.AgentFSController.GetLatestSnapshot:input_type -> agentfs.v1alpha1.GetLatestSnapshotRequest
	2,  // 5: agentfs.v1alpha1.AgentFSController.UploadSnapshot:input_type -> agentfs.v1alpha1.UploadSnapshotRequest
	6,  // 6: agentfs.v1alpha1.AgentFSController.UploadBlob:input_type -> agentfs.v1alpha1.UploadBlobRequest
	8,  // 7: agentfs.v1alpha1.AgentFSController.DownloadBlob:input_type -> agentfs.v1alpha1.DownloadBlobRequest
	10, // 8: agentfs.v1alpha1.AgentFSController.HasBlob:input_type -> agentfs.v1alpha1.HasBlobRequest
	1,  // 9: agentfs.v1alpha1.AgentFSController.GetLatestSnapshot:output_type -> agentfs.v1alpha1.GetLatestSnapshotResponse
	3,  // 10: agentfs.v1alpha1.AgentFSController.UploadSnapshot:output_type -> agentfs.v1alpha1.UploadSnapshotResponse
	7,  // 11: agentfs.v1alpha1.AgentFSController.UploadBlob:output_type -> agentfs.v1alpha1.UploadBlobResponse
	9,  // 12: agentfs.v1alpha1.AgentFSController.DownloadBlob:output_type -> agentfs.v1alpha1.DownloadBlobResponse
	11, // 13: agentfs.v1alpha1.AgentFSController.HasBlob:output_type -> agentfs.v1alpha1.HasBlobResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_agentfs_proto_init() }
func file_agentfs_proto_init() {
	if File_agentfs_proto != nil {
		return
	}
	file_agentfs_proto_msgTypes[6].OneofWrappers = []any{
		(*UploadBlobRequest_Sha256)(nil),
		(*UploadBlobRequest_Content)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentfs_proto_rawDesc), len(file_agentfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentfs_proto_goTypes,
		DependencyIndexes: file_agentfs_proto_depIdxs,
		MessageInfos:      file_agentfs_proto_msgTypes,
	}.Build()
	File_agentfs_proto = out.File
	file_agentfs_proto_goTypes = nil
	file_agentfs_proto_depIdxs = nil
}
