// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: agentfs.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentFSController_GetLatestSnapshot_FullMethodName = "/agentfs.v1alpha1.AgentFSController/GetLatestSnapshot"
	AgentFSController_UploadSnapshot_FullMethodName    = "/agentfs.v1alpha1.AgentFSController/UploadSnapshot"
	AgentFSController_UploadBlob_FullMethodName        = "/agentfs.v1alpha1.AgentFSController/UploadBlob"
	AgentFSController_DownloadBlob_FullMethodName      = "/agentfs.v1alpha1.AgentFSController/DownloadBlob"
	AgentFSController_HasBlob_FullMethodName           = "/agentfs.v1alpha1.AgentFSController/HasBlob"
)

// AgentFSControllerClient is the client API for AgentFSController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentFSControllerClient interface {
	GetLatestSnapshot(ctx context.Context, in *GetLatestSnapshotRequest, opts ...grpc.CallOption) (*GetLatestSnapshotResponse, error)
	UploadSnapshot(ctx context.Context, in *UploadSnapshotRequest, opts ...grpc.CallOption) (*UploadSnapshotResponse, error)
	UploadBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadBlobRequest, UploadBlobResponse], error)
	DownloadBlob(ctx context.Context, in *DownloadBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadBlobResponse], error)
	HasBlob(ctx context.Context, in *HasBlobRequest, opts ...grpc.CallOption) (*HasBlobResponse, error)
}

type agentFSControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentFSControllerClient(cc grpc.ClientConnInterface) AgentFSControllerClient {
	return &agentFSControllerClient{cc}
}

func (c *agentFSControllerClient) GetLatestSnapshot(ctx context.Context, in *GetLatestSnapshotRequest, opts ...grpc.CallOption) (*GetLatestSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestSnapshotResponse)
	err := c.cc.Invoke(ctx, AgentFSController_GetLatestSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentFSControllerClient) UploadSnapshot(ctx context.Context, in *UploadSnapshotRequest, opts ...grpc.CallOption) (*UploadSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSnapshotResponse)
	err := c.cc.Invoke(ctx, AgentFSController_UploadSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentFSControllerClient) UploadBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadBlobRequest, UploadBlobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentFSController_ServiceDesc.Streams[0], AgentFSController_UploadBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadBlobRequest, UploadBlobResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentFSController_UploadBlobClient = grpc.ClientStreamingClient[UploadBlobRequest, UploadBlobResponse]

func (c *agentFSControllerClient) DownloadBlob(ctx context.Context, in *DownloadBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadBlobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentFSController_ServiceDesc.Streams[1], AgentFSController_DownloadBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadBlobRequest, DownloadBlobResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentFSController_DownloadBlobClient = grpc.ServerStreamingClient[DownloadBlobResponse]

func (c *agentFSControllerClient) HasBlob(ctx context.Context, in *HasBlobRequest, opts ...grpc.CallOption) (*HasBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasBlobResponse)
	err := c.cc.Invoke(ctx, AgentFSController_HasBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentFSControllerServer is the server API for AgentFSController service.
// All implementations must embed UnimplementedAgentFSControllerServer
// for forward compatibility.
type AgentFSControllerServer interface {
	GetLatestSnapshot(context.Context, *GetLatestSnapshotRequest) (*GetLatestSnapshotResponse, error)
	UploadSnapshot(context.Context, *UploadSnapshotRequest) (*UploadSnapshotResponse, error)
	UploadBlob(grpc.ClientStreamingServer[UploadBlobRequest, UploadBlobResponse]) error
	DownloadBlob(*DownloadBlobRequest, grpc.ServerStreamingServer[DownloadBlobResponse]) error
	HasBlob(context.Context, *HasBlobRequest) (*HasBlobResponse, error)
	mustEmbedUnimplementedAgentFSControllerServer()
}

// UnimplementedAgentFSControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentFSControllerServer struct{}

func (UnimplementedAgentFSControllerServer) GetLatestSnapshot(context.Context, *GetLatestSnapshotRequest) (*GetLatestSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestSnapshot not implemented")
}
func (UnimplementedAgentFSControllerServer) UploadSnapshot(context.Context, *UploadSnapshotRequest) (*UploadSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadSnapshot not implemented")
}
func (UnimplementedAgentFSControllerServer) UploadBlob(grpc.ClientStreamingServer[UploadBlobRequest, UploadBlobResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadBlob not implemented")
}
func (UnimplementedAgentFSControllerServer) DownloadBlob(*DownloadBlobRequest, grpc.ServerStreamingServer[DownloadBlobResponse]) error {
	return status.Error(codes.Unimplemented, "method DownloadBlob not implemented")
}
func (UnimplementedAgentFSControllerServer) HasBlob(context.Context, *HasBlobRequest) (*HasBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasBlob not implemented")
}
func (UnimplementedAgentFSControllerServer) mustEmbedUnimplementedAgentFSControllerServer() {}
func (UnimplementedAgentFSControllerServer) testEmbeddedByValue()                           {}

// UnsafeAgentFSControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentFSControllerServer will
// result in compilation errors.
type UnsafeAgentFSControllerServer interface {
	mustEmbedUnimplementedAgentFSControllerServer()
}

func RegisterAgentFSControllerServer(s grpc.ServiceRegistrar, srv AgentFSControllerServer) {
	// If the following call panics, it indicates UnimplementedAgentFSControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentFSController_ServiceDesc, srv)
}

func _AgentFSController_GetLatestSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentFSControllerServer).GetLatestSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentFSController_GetLatestSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentFSControllerServer).GetLatestSnapshot(ctx, req.(*GetLatestSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentFSController_UploadSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentFSControllerServer).UploadSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentFSController_UploadSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentFSControllerServer).UploadSnapshot(ctx, req.(*UploadSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentFSController_UploadBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentFSControllerServer).UploadBlob(&grpc.GenericServerStream[UploadBlobRequest, UploadBlobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentFSController_UploadBlobServer = grpc.ClientStreamingServer[UploadBlobRequest, UploadBlobResponse]

func _AgentFSController_DownloadBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadBlobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentFSControllerServer).DownloadBlob(m, &grpc.GenericServerStream[DownloadBlobRequest, DownloadBlobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentFSController_DownloadBlobServer = grpc.ServerStreamingServer[DownloadBlobResponse]

func _AgentFSController_HasBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentFSControllerServer).HasBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentFSController_HasBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentFSControllerServer).HasBlob(ctx, req.(*HasBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentFSController_ServiceDesc is the grpc.ServiceDesc for AgentFSController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentFSController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentfs.v1alpha1.AgentFSController",
	HandlerType: (*AgentFSControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestSnapshot",
			Handler:    _AgentFSController_GetLatestSnapshot_Handler,
		},
		{
			MethodName: "UploadSnapshot",
			Handler:    _AgentFSController_UploadSnapshot_Handler,
		},
		{
			MethodName: "HasBlob",
			Handler:    _AgentFSController_HasBlob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadBlob",
			Handler:       _AgentFSController_UploadBlob_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadBlob",
			Handler:       _AgentFSController_DownloadBlob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agentfs.proto",
}
